language: python
python:
    - 3.7 # Pinned since tensorflow 1.x is not available for python > 3.7

cache:
  directories:
    - $HOME/.cache/pre-commit

addons:
  apt:
    packages:
      - pandoc

install: pip install -U poetry tox-travis codecov coverage travis-sphinx
script: tox
after_success: coverage combine && codecov

stages:
  - test
  - docs
  - name: deploy

jobs:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=test1
    - python: 3.7
      env: TOXENV=test2
    - python: 3.7
      env: TOXENV=test3
    - python: 3.7
      env: TOXENV=test4
    - python: 3.7
      env: TOXENV=lint
    - stage: docs
      python: 3.7
      env: TOXENV=docs

before_deploy:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config pypi-token.pypi $PYPI_PASSWORD

deploy:
  - provider: script
    script: poetry publish -v --build
    on:
      tags: true
      python: 3.7
      repo: kiudee/cs-ranking
      branch: master
