language: python

cache:
  directories:
    - $HOME/miniconda3

before_install:
  - . ./scripts/install_miniconda.sh

install:
  - . ./scripts/create_testenv.sh

script:
  - pytest -v --cov=csrank --ignore experiments
