language: python

cache:
  directories:
    - $HOME/miniconda3

addons:
  apt_packages:
    - pandoc

before_install:
  - . ./scripts/install_miniconda.sh

install:
  - . ./scripts/create_testenv.sh
  - conda install --yes sphinx ipython
  - pip install -I git+https://github.com/Syntaf/travis-sphinx.git
  - pip install coveralls nbsphinx sphinx_rtd_theme

env:
  - TESTCMD="--cov-append csrank/tests/test_choice_functions.py"
  - TESTCMD="--cov-append csrank/tests/test_discrete_choice.py"
  - TESTCMD="--cov-append csrank/tests/test_ranking.py"
  - TESTCMD="--cov-append csrank/tests/test_fate.py csrank/tests/test_losses.py csrank/tests/test_metrics.py csrank/tests/test_tuning.py csrank/tests/test_util.py csrank/tests/test_tuning.py csrank/tests/test_callback.py"

script:
  - pytest -v --cov=csrank --ignore experiments $TESTCMD
  - travis-sphinx build -n --source=docs

after_success:
  - coveralls
  - travis-sphinx deploy
